name: prefect_pipeline
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - prefect[aws, viz]
  - coiled
  - boto3
  - dask
  - pandas
  - pymongo
  - pip:
    - pandas-gbq>=0.12
    - paramiko
